name: Test Windows Compatibility

on:
  push:
    branches:
      - main
    paths:
      - 'cli/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cli/**'

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Build CLI
        working-directory: cli
        run: bun run build

      - name: Test build command (debug mode)
        working-directory: games/mewsterpiece
        shell: pwsh
        run: |
          # Test the build command with debug output
          ../../cli/dist/index.js build --debug
          # Check if zip files were created and have content
          Get-ChildItem *.zip | ForEach-Object {
            Write-Host "Checking $($_.Name)..."
            $size = $_.Length
            Write-Host "Size: $size bytes"
            if ($size -lt 100) {
              Write-Error "ERROR: $($_.Name) is too small ($size bytes) - likely empty archive"
              exit 1
            }
          }

      - name: Test create command
        shell: pwsh
        run: |
          # Test creating a new game
          cli/dist/index.js create test-windows-game
          cd test-windows-game
          # Try building the new game
          ../../cli/dist/index.js build --debug
          # Check the created zip files
          Get-ChildItem *.zip | ForEach-Object {
            Write-Host "Checking $($_.Name)..."
            $size = $_.Length
            Write-Host "Size: $size bytes"
            if ($size -lt 100) {
              Write-Error "ERROR: $($_.Name) is too small ($size bytes) - likely empty archive"
              exit 1
            }
          }
